version: '3.7'

services:
  tubesync:
    image: ghcr.io/meeb/tubesync:latest
    container_name: tubesync
    restart: unless-stopped
    ports:
      - 4848:4848
    volumes:
      - /home/umbrel/umbrel/data/storage/my-apps-config/tubesync-config:/config
      - /home/umbrel/umbrel/data/storage/tubesync:/downloads
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000	 